created creator landing page and added base components to it
MikaelCarpenter/NFT-Club pull request #8
Opened 2022-03-14 17:24 UTC by migui3230

lmk if there are any changes you want in here especially with how the box looks and the fonts on the page

2022-03-14 19:01 UTC, MikaelCarpenter reviewed
One other thing to mention, the way Next routing works is that they use the filename (case-sensitive) for the route. So right now this route would be `localhost:3000/creatorLandingPage/`. I would suggest changing the filename to be "kebab-case" because that's more typical for domain routes. i.e. `/creator-landing-page/`

2022-03-14 19:45 UTC, migui3230 commented
![image](https://user-images.githubusercontent.com/74937076/158249102-68206eb2-0c5f-440f-ac89-10c7b303a468.png)

2022-03-15 00:21 UTC, migui3230 commented on app/pages/creatorLandingPage.tsx
> +import BenefitBox from "./components/BenefitBox";
@MikaelCarpenter do you want me to delete those component files after pulling them in? Also do you know what `Nextpage` is used for?

2022-03-15 00:42 UTC, migui3230 commented
![image](https://user-images.githubusercontent.com/74937076/158283884-384512ed-5919-4e43-b972-f2a63458f396.png)

new page after changes

2022-03-15 18:37 UTC, MikaelCarpenter commented on app/pages/creatorLandingPage.tsx
> +import BenefitBox from "./components/BenefitBox";
Yea go ahead and delete them. And I saw you moved the component definition into the page file, but you can just not make them components at all. Like all of the JSX should just be a part of `CreatorLandingPage` component

I'm pretty sure `NextPage` is just a TypeScript type that they give you, but you don't have to use it

2022-03-15 18:43 UTC, MikaelCarpenter commented
Looking at the merge conflicts, you're going to want to rebase this off of the most recent `main` branch. It'll get you the latest changes which already included the `@tailwindcss/typography` module and added it to the config

Here's some docs on what a rebase is: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

They make it sound all complicated but you'll just want to do:
```bash
# make sure you have the latest main branch
git fetch

# rebase on top of the latest main branch
git rebase origin/main

# The above command will likely pause and tell you to resolve merge conflicts
# After you adjust the code to remove those conflicts you'll
git add <path to file you touched>
git rebase --continue

# Repeat until rebase is complete
```

2022-03-15 18:57 UTC, NBNARADHYA commented
@migui3230 Please fix the linting changes.

I think it exists mainly in `yarn.lock`. You could first undo changes, then do `yarn add package1 package2 ...`. Also keep the format on save to false if you are using vs code.

2022-03-15 18:59 UTC, NBNARADHYA requested changes
@migui3230 Please fix the linting changes.

I think it exists mainly in `yarn.lock`. You could first undo changes, then do `yarn add package1 package2 ...`. Also keep the format on save to false if you are using vs code.

2022-03-15 19:44 UTC, MikaelCarpenter approved these changes
Looks good !

2022-03-15 19:44 UTC, merged